application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "eureka"
openid:
  auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
  token_url: "https://www.googleapis.com/oauth2/v3/token"
  user_info_url: "https://openidconnect.googleapis.com/v1/userinfo"
